version: "3.3"

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: unpin
      POSTGRES_USER: unpin-bot
      POSTGRES_PASSWORD: example
